[root@ip-172-31-1-174 aws-ansible]# cat aws_ec2_new.yml
---
- name: Create a new Demo EC2 instance
  hosts: local
  connection: local
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-041db4a969fe3eb68  # Amazon Linux
      keypair: 11Nov21 # pem file name

  vars_files:
     - pass.yml
  tasks:

    - name: Create an ec2 instance
      ec2:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: M-Demo
         instance_tags:
            Name: M-Demo
         vpc_subnet_id: subnet-037e3db5f092dd8b1
         assign_public_ip: yes
      register: ec2_out

   #- name: Add new instance to host group
   #   add_host:
   #    hostname: "{{ item.public_ip }}"
   #    groupname: newserver
   #   loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
       host: "{{ item.public_dns_name }}"
       port: 22
       state: started
      with_items: '{{ec2_out.instances}}'
    #  loop: "{{ ec2.instances }}"
    - name: adding to ansible hosts
      add_host: hostname={{ item.public_dns_name }} groups=ec2hosts
      with_items: '{{ ec2_out.instances }}'
- hosts: ec2hosts
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i 11Nov21.pem'
  remote_user: ec2-user
  become: true
  become_method: sudo
  roles:
   -  httpdserver
